# Base configs
baseurl: "https://xecreth-svg.github.io/photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Candles by Lucija"
subtitle: "insert subtitle"
author: "Lucija Filiovic"
header:
 title: "Candles"
 subtitle: "by Lucy"
footer:
 name: "Hey there, my name is Lucy"
 bio: "insert more bio."
 github: ""
web_design: "MC"

social_urls:
  twitter: ""
  instagram: "https://www.instagram.com/slatka.iskra/"
  dribbble: ""
  linkedin: ""
  github: ""

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
